{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ire\n"
     ]
    }
   ],
   "source": [
    "print('ire')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "   WARNING: Do not use the development server in a production environment.\n",
      "   Use a production WSGI server instead.\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [24/Mar/2019 11:10:52] \"\u001b[33mGET / HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 11:10:54] \"\u001b[33mGET /favicon.ico HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 11:10:57] \"\u001b[37mGET /home HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 11:10:57] \"\u001b[37mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 11:10:57] \"\u001b[37mGET /static/css/jumbotron-narrow.css HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 11:11:00] \"\u001b[37mGET /showSignUp HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 11:11:00] \"\u001b[37mGET /static/js/signUp.js HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 11:11:00] \"\u001b[37mGET /static/css/style.css HTTP/1.1\u001b[0m\" 200 -\n",
      "[2019-03-24 11:11:04,857] ERROR in app: Exception on /signUp [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 13, in signUp\n",
      "    return json.dumps({'html':'<span>All fields good!</span>'})\n",
      "NameError: name 'json' is not defined\n",
      "127.0.0.1 - - [24/Mar/2019 11:11:05] \"\u001b[1m\u001b[35mPOST /signUp HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "yes u r here\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/Mar/2019 11:11:05] \"\u001b[37mPOST /user HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:00:42] \"\u001b[33mGET / HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:00:47] \"\u001b[37mGET /home HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:00:49] \"\u001b[37mGET /showSignUp HTTP/1.1\u001b[0m\" 200 -\n",
      "[2019-03-24 12:00:53,390] ERROR in app: Exception on /signUp [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 13, in signUp\n",
      "    return json.dumps({'html':'<span>All fields good!</span>'})\n",
      "NameError: name 'json' is not defined\n",
      "127.0.0.1 - - [24/Mar/2019 12:00:53] \"\u001b[1m\u001b[35mPOST /signUp HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:00:53] \"\u001b[37mPOST /user HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "yes u r here\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[2019-03-24 12:00:58,143] ERROR in app: Exception on /signUp [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 13, in signUp\n",
      "    return json.dumps({'html':'<span>All fields good!</span>'})\n",
      "NameError: name 'json' is not defined\n",
      "127.0.0.1 - - [24/Mar/2019 12:00:58] \"\u001b[1m\u001b[35mPOST /signUp HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:00:58] \"\u001b[37mPOST /tweets HTTP/1.1\u001b[0m\" 200 -\n",
      "[2019-03-24 12:01:05,620] ERROR in app: Exception on /signUp [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 13, in signUp\n",
      "    return json.dumps({'html':'<span>All fields good!</span>'})\n",
      "NameError: name 'json' is not defined\n",
      "127.0.0.1 - - [24/Mar/2019 12:01:05] \"\u001b[1m\u001b[35mPOST /signUp HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:01:05] \"\u001b[37mPOST /tweets HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:01:11] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "[2019-03-24 12:01:18,793] ERROR in app: Exception on /signUp [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 13, in signUp\n",
      "    return json.dumps({'html':'<span>All fields good!</span>'})\n",
      "NameError: name 'json' is not defined\n",
      "127.0.0.1 - - [24/Mar/2019 12:01:18] \"\u001b[1m\u001b[35mPOST /signUp HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:01:19] \"\u001b[37mPOST /tweets HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:01:19] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:03:24] \"\u001b[37mGET /home HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:03:26] \"\u001b[37mGET /showSignUp HTTP/1.1\u001b[0m\" 200 -\n",
      "[2019-03-24 12:03:29,345] ERROR in app: Exception on /signUp [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 13, in signUp\n",
      "    return json.dumps({'html':'<span>All fields good!</span>'})\n",
      "NameError: name 'json' is not defined\n",
      "127.0.0.1 - - [24/Mar/2019 12:03:29] \"\u001b[37mPOST /user HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:03:29] \"\u001b[1m\u001b[35mPOST /signUp HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "yes u r here\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[2019-03-24 12:03:33,616] ERROR in app: Exception on /signUp [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 13, in signUp\n",
      "    return json.dumps({'html':'<span>All fields good!</span>'})\n",
      "NameError: name 'json' is not defined\n",
      "127.0.0.1 - - [24/Mar/2019 12:03:33] \"\u001b[1m\u001b[35mPOST /signUp HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:03:33] \"\u001b[37mPOST /tweets HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:03:41] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:05:01] \"\u001b[37mGET /home HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:05:01] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:05:09] \"\u001b[37mGET /showSignUp HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:05:09] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "[2019-03-24 12:05:16,999] ERROR in app: Exception on /signUp [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 13, in signUp\n",
      "    return json.dumps({'html':'<span>All fields good!</span>'})\n",
      "NameError: name 'json' is not defined\n",
      "127.0.0.1 - - [24/Mar/2019 12:05:17] \"\u001b[37mPOST /user HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:05:17] \"\u001b[1m\u001b[35mPOST /signUp HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "yes u r here\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/Mar/2019 12:05:17] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "[2019-03-24 12:05:36,784] ERROR in app: Exception on /signUp [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 13, in signUp\n",
      "    return json.dumps({'html':'<span>All fields good!</span>'})\n",
      "NameError: name 'json' is not defined\n",
      "127.0.0.1 - - [24/Mar/2019 12:05:36] \"\u001b[1m\u001b[35mPOST /signUp HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:05:36] \"\u001b[37mPOST /tweets HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:05:37] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:08:26] \"\u001b[37mGET /home HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:08:26] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:08:31] \"\u001b[37mGET /showSignUp HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:08:31] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "[2019-03-24 12:08:36,065] ERROR in app: Exception on /signUp [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 13, in signUp\n",
      "    return json.dumps({'html':'<span>All fields good!</span>'})\n",
      "NameError: name 'json' is not defined\n",
      "127.0.0.1 - - [24/Mar/2019 12:08:36] \"\u001b[1m\u001b[35mPOST /signUp HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:08:36] \"\u001b[37mPOST /user HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "yes u r here\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/Mar/2019 12:08:36] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:11:29] \"\u001b[37mGET /home HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:11:30] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:11:37] \"\u001b[37mGET /showSignUp HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:11:37] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "[2019-03-24 12:11:41,095] ERROR in app: Exception on /signUp [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 13, in signUp\n",
      "    return json.dumps({'html':'<span>All fields good!</span>'})\n",
      "NameError: name 'json' is not defined\n",
      "127.0.0.1 - - [24/Mar/2019 12:11:41] \"\u001b[1m\u001b[35mPOST /signUp HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:11:41] \"\u001b[37mPOST /user HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "yes u r here\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/Mar/2019 12:11:41] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:12:05] \"\u001b[37mGET /home HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:12:05] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:12:06] \"\u001b[37mGET /home HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:12:06] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:12:12] \"\u001b[37mGET /showSignUp HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:12:12] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:12:18] \"\u001b[37mGET /showSignUp HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:12:18] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "[2019-03-24 12:12:34,567] ERROR in app: Exception on /signUp [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 15, in signUp\n",
      "    return json.dumps({'html':'<span>Enter the required fields</span>'})\n",
      "NameError: name 'json' is not defined\n",
      "127.0.0.1 - - [24/Mar/2019 12:12:34] \"\u001b[1m\u001b[35mPOST /signUp HTTP/1.1\u001b[0m\" 500 -\n",
      "[2019-03-24 12:12:53,788] ERROR in app: Exception on /signUp [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 13, in signUp\n",
      "    return json.dumps({'html':'<span>All fields good!</span>'})\n",
      "NameError: name 'json' is not defined\n",
      "127.0.0.1 - - [24/Mar/2019 12:12:53] \"\u001b[1m\u001b[35mPOST /signUp HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:12:53] \"\u001b[37mPOST /user HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "yes u r here\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/Mar/2019 12:12:54] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:14:33] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "[2019-03-24 12:14:48,061] ERROR in app: Exception on /signUp [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 13, in signUp\n",
      "    return json.dumps({'html':'<span>All fields good!</span>'})\n",
      "NameError: name 'json' is not defined\n",
      "127.0.0.1 - - [24/Mar/2019 12:14:48] \"\u001b[1m\u001b[35mPOST /signUp HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:14:48] \"\u001b[37mPOST /user HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "yes u r here\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/Mar/2019 12:14:48] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:17:12] \"\u001b[33mGET / HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:17:16] \"\u001b[37mGET /home HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:17:18] \"\u001b[37mGET /showSignUp HTTP/1.1\u001b[0m\" 200 -\n",
      "[2019-03-24 12:17:21,818] ERROR in app: Exception on /signUp [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 13, in signUp\n",
      "    return json.dumps({'html':'<span>All fields good!</span>'})\n",
      "NameError: name 'json' is not defined\n",
      "127.0.0.1 - - [24/Mar/2019 12:17:21] \"\u001b[1m\u001b[35mPOST /signUp HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:17:21] \"\u001b[37mPOST /user HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "yes u r here\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[2019-03-24 12:17:25,216] ERROR in app: Exception on /signUp [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 13, in signUp\n",
      "    return json.dumps({'html':'<span>All fields good!</span>'})\n",
      "NameError: name 'json' is not defined\n",
      "127.0.0.1 - - [24/Mar/2019 12:17:25] \"\u001b[1m\u001b[35mPOST /signUp HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:17:25] \"\u001b[37mPOST /tweets HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:17:33] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:17:51] \"\u001b[37mPOST /tweets HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:17:51] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:17:54] \"\u001b[37mPOST /tweets HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:17:55] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:17:55] \"\u001b[37mPOST /tweets HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:17:55] \"\u001b[37mPOST /tweets HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:17:55] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:17:55] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:18:41] \"\u001b[37mPOST /tweets HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:18:42] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:18:45] \"\u001b[37mPOST /tweets HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:18:45] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:18:45] \"\u001b[37mPOST /tweets HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:18:45] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:18:49] \"\u001b[37mPOST /tweets HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:18:49] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:19:31] \"\u001b[33mGET / HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:19:36] \"\u001b[37mGET /home HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:19:38] \"\u001b[37mGET /showSignUp HTTP/1.1\u001b[0m\" 200 -\n",
      "[2019-03-24 12:19:40,852] ERROR in app: Exception on /signUp [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 13, in signUp\n",
      "    return json.dumps({'html':'<span>All fields good!</span>'})\n",
      "NameError: name 'json' is not defined\n",
      "127.0.0.1 - - [24/Mar/2019 12:19:40] \"\u001b[1m\u001b[35mPOST /signUp HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:19:40] \"\u001b[37mPOST /user HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "yes u r here\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[2019-03-24 12:19:44,841] ERROR in app: Exception on /signUp [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 13, in signUp\n",
      "    return json.dumps({'html':'<span>All fields good!</span>'})\n",
      "NameError: name 'json' is not defined\n",
      "127.0.0.1 - - [24/Mar/2019 12:19:44] \"\u001b[1m\u001b[35mPOST /signUp HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:19:44] \"\u001b[37mPOST /tweets HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:19:50] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:19:58] \"\u001b[37mPOST /tweets HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:19:58] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:20:18] \"\u001b[1m\u001b[31mGET /tweets HTTP/1.1\u001b[0m\" 405 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:20:31] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:20:32] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:20:35] \"\u001b[37mGET /showSignUp HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:20:35] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "[2019-03-24 12:20:41,964] ERROR in app: Exception on /signUp [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 13, in signUp\n",
      "    return json.dumps({'html':'<span>All fields good!</span>'})\n",
      "NameError: name 'json' is not defined\n",
      "127.0.0.1 - - [24/Mar/2019 12:20:41] \"\u001b[1m\u001b[35mPOST /signUp HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:20:42] \"\u001b[37mPOST /user HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "yes u r here\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/Mar/2019 12:20:42] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "[2019-03-24 12:20:49,711] ERROR in app: Exception on /signUp [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 13, in signUp\n",
      "    return json.dumps({'html':'<span>All fields good!</span>'})\n",
      "NameError: name 'json' is not defined127.0.0.1 - - [24/Mar/2019 12:20:49] \"\u001b[37mPOST /tweets HTTP/1.1\u001b[0m\" 200 -\n",
      "\n",
      "127.0.0.1 - - [24/Mar/2019 12:20:49] \"\u001b[1m\u001b[35mPOST /signUp HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:20:50] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:21:43] \"\u001b[37mGET /home HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:21:43] \"\u001b[37mGET /static/css/jumbotron-narrow.css HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:21:43] \"\u001b[37mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:21:44] \"\u001b[37mGET /showSignUp HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:21:44] \"\u001b[37mGET /static/css/style.css HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:21:44] \"\u001b[37mGET /static/js/signUp.js HTTP/1.1\u001b[0m\" 200 -\n",
      "[2019-03-24 12:21:50,872] ERROR in app: Exception on /signUp [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 13, in signUp\n",
      "    return json.dumps({'html':'<span>All fields good!</span>'})\n",
      "NameError: name 'json' is not defined\n",
      "127.0.0.1 - - [24/Mar/2019 12:21:50] \"\u001b[1m\u001b[35mPOST /signUp HTTP/1.1\u001b[0m\" 500 -\n",
      "[2019-03-24 12:21:50,897] ERROR in app: Exception on /user [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 25, in lookup\n",
      "    session['tweets'].append(tweet)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\werkzeug\\local.py\", line 377, in <lambda>\n",
      "    __getitem__ = lambda x, i: x._get_current_object()[i]\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\sessions.py\", line 83, in __getitem__\n",
      "    return super(SecureCookieSession, self).__getitem__(key)\n",
      "KeyError: 'tweets'\n",
      "127.0.0.1 - - [24/Mar/2019 12:21:50] \"\u001b[1m\u001b[35mPOST /user HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "yes u r here\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/Mar/2019 12:22:13] \"\u001b[37mGET /showSignUp HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:22:13] \"\u001b[37mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:22:14] \"\u001b[37mGET /static/css/jumbotron-narrow.css HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:22:14] \"\u001b[37mGET /static/css/style.css HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:22:14] \"\u001b[37mGET /static/js/signUp.js HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:22:15] \"\u001b[1m\u001b[31mGET /user HTTP/1.1\u001b[0m\" 400 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:22:15] \"\u001b[37mGET /showSignUp HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:22:15] \"\u001b[37mGET /home HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:22:15] \"\u001b[37mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:22:15] \"\u001b[37mGET /static/css/style.css HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:22:15] \"\u001b[37mGET /static/css/jumbotron-narrow.css HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "yes u r here\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/Mar/2019 12:22:15] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "[2019-03-24 12:22:32,640] ERROR in app: Exception on /signUp [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 13, in signUp\n",
      "    return json.dumps({'html':'<span>All fields good!</span>'})\n",
      "NameError: name 'json' is not defined\n",
      "127.0.0.1 - - [24/Mar/2019 12:22:32] \"\u001b[1m\u001b[35mPOST /signUp HTTP/1.1\u001b[0m\" 500 -\n",
      "[2019-03-24 12:22:32,681] ERROR in app: Exception on /user [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 25, in lookup\n",
      "    session['tweets'].append(tweet)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\werkzeug\\local.py\", line 377, in <lambda>\n",
      "    __getitem__ = lambda x, i: x._get_current_object()[i]\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\sessions.py\", line 83, in __getitem__\n",
      "    return super(SecureCookieSession, self).__getitem__(key)\n",
      "KeyError: 'tweets'\n",
      "127.0.0.1 - - [24/Mar/2019 12:22:32] \"\u001b[1m\u001b[35mPOST /user HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "yes u r here\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/Mar/2019 12:23:20] \"\u001b[37mGET /home HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:23:23] \"\u001b[37mGET /showSignUp HTTP/1.1\u001b[0m\" 200 -\n",
      "[2019-03-24 12:23:26,480] ERROR in app: Exception on /signUp [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 13, in signUp\n",
      "    return json.dumps({'html':'<span>All fields good!</span>'})\n",
      "NameError: name 'json' is not defined\n",
      "127.0.0.1 - - [24/Mar/2019 12:23:26] \"\u001b[1m\u001b[35mPOST /signUp HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:23:26] \"\u001b[37mPOST /user HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "yes u r here\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[2019-03-24 12:23:31,610] ERROR in app: Exception on /signUp [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 13, in signUp\n",
      "    return json.dumps({'html':'<span>All fields good!</span>'})\n",
      "NameError: name 'json' is not defined\n",
      "127.0.0.1 - - [24/Mar/2019 12:23:31] \"\u001b[37mPOST /tweets HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:23:31] \"\u001b[1m\u001b[35mPOST /signUp HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:23:36] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "[2019-03-24 12:23:40,600] ERROR in app: Exception on /signUp [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 13, in signUp\n",
      "    return json.dumps({'html':'<span>All fields good!</span>'})\n",
      "NameError: name 'json' is not defined\n",
      "127.0.0.1 - - [24/Mar/2019 12:23:40] \"\u001b[1m\u001b[35mPOST /signUp HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:23:40] \"\u001b[37mPOST /tweets HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:23:40] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:24:14] \"\u001b[1m\u001b[31mGET /tweets HTTP/1.1\u001b[0m\" 405 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:24:33] \"\u001b[33mGET / HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:24:38] \"\u001b[37mGET /home HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:24:42] \"\u001b[33mGET / HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:24:54] \"\u001b[37mGET /home HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:24:55] \"\u001b[37mGET /home HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:24:55] \"\u001b[37mGET /home HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:24:55] \"\u001b[37mGET /home HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:24:56] \"\u001b[37mGET /home HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:24:56] \"\u001b[37mGET /home HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:24:56] \"\u001b[37mGET /home HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:25:07] \"\u001b[37mGET /home HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:25:09] \"\u001b[37mGET /home HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:25:15] \"\u001b[37mGET /home HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:25:15] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:27:54] \"\u001b[33mGET / HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:27:56] \"\u001b[33mGET /favicon.ico HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:28:00] \"\u001b[37mGET /home HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:28:01] \"\u001b[37mGET /static/css/bootstrap.min.css HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:28:01] \"\u001b[37mGET /static/css/jumbotron-narrow.css HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:28:05] \"\u001b[33mGET /seriouslykill HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:28:11] \"\u001b[37mGET /home HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:28:13] \"\u001b[37mGET /showSignUp HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:28:13] \"\u001b[37mGET /static/css/style.css HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:28:13] \"\u001b[37mGET /static/js/signUp.js HTTP/1.1\u001b[0m\" 200 -\n",
      "[2019-03-24 12:28:16,804] ERROR in app: Exception on /signUp [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 13, in signUp\n",
      "    return json.dumps({'html':'<span>All fields good!</span>'})\n",
      "NameError: name 'json' is not defined\n",
      "127.0.0.1 - - [24/Mar/2019 12:28:16] \"\u001b[1m\u001b[35mPOST /signUp HTTP/1.1\u001b[0m\" 500 -\n",
      "[2019-03-24 12:28:17,155] ERROR in app: Exception on /user [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 25, in lookup\n",
      "    session['tweets'].append(tweet)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\werkzeug\\local.py\", line 377, in <lambda>\n",
      "    __getitem__ = lambda x, i: x._get_current_object()[i]\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\sessions.py\", line 83, in __getitem__\n",
      "    return super(SecureCookieSession, self).__getitem__(key)\n",
      "KeyError: 'tweets'\n",
      "127.0.0.1 - - [24/Mar/2019 12:28:17] \"\u001b[1m\u001b[35mPOST /user HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "yes u r here\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/Mar/2019 12:28:34] \"\u001b[37mGET /home HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:28:34] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:28:41] \"\u001b[37mGET /showSignUp HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:28:41] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "[2019-03-24 12:28:56,562] ERROR in app: Exception on /user [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 25, in lookup\n",
      "    session['tweets'].append(tweet)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\werkzeug\\local.py\", line 377, in <lambda>\n",
      "    __getitem__ = lambda x, i: x._get_current_object()[i]\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\sessions.py\", line 83, in __getitem__\n",
      "    return super(SecureCookieSession, self).__getitem__(key)\n",
      "KeyError: 'tweets'\n",
      "127.0.0.1 - - [24/Mar/2019 12:28:56] \"\u001b[1m\u001b[35mPOST /user HTTP/1.1\u001b[0m\" 500 -\n",
      "[2019-03-24 12:28:56,581] ERROR in app: Exception on /signUp [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 13, in signUp\n",
      "    return json.dumps({'html':'<span>All fields good!</span>'})\n",
      "NameError: name 'json' is not defined\n",
      "127.0.0.1 - - [24/Mar/2019 12:28:56] \"\u001b[1m\u001b[35mPOST /signUp HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "yes u r here\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/Mar/2019 12:29:04] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:29:04] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:29:05] \"\u001b[37mGET /showSignUp HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:29:06] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "[2019-03-24 12:29:07,276] ERROR in app: Exception on /signUp [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 15, in signUp\n",
      "    return json.dumps({'html':'<span>Enter the required fields</span>'})\n",
      "NameError: name 'json' is not defined\n",
      "127.0.0.1 - - [24/Mar/2019 12:29:07] \"\u001b[1m\u001b[35mPOST /signUp HTTP/1.1\u001b[0m\" 500 -\n",
      "[2019-03-24 12:29:17,807] ERROR in app: Exception on /user [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 25, in lookup\n",
      "    session['tweets'].append(tweet)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\werkzeug\\local.py\", line 377, in <lambda>\n",
      "    __getitem__ = lambda x, i: x._get_current_object()[i]\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\sessions.py\", line 83, in __getitem__\n",
      "    return super(SecureCookieSession, self).__getitem__(key)\n",
      "KeyError: 'tweets'\n",
      "127.0.0.1 - - [24/Mar/2019 12:29:17] \"\u001b[1m\u001b[35mPOST /user HTTP/1.1\u001b[0m\" 500 -\n",
      "[2019-03-24 12:29:17,819] ERROR in app: Exception on /signUp [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 13, in signUp\n",
      "    return json.dumps({'html':'<span>All fields good!</span>'})\n",
      "NameError: name 'json' is not defined\n",
      "127.0.0.1 - - [24/Mar/2019 12:29:17] \"\u001b[1m\u001b[35mPOST /signUp HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "yes u r here\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/Mar/2019 12:29:54] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:29:56] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:29:58] \"\u001b[37mGET /showSignUp HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:29:59] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "[2019-03-24 12:30:07,907] ERROR in app: Exception on /user [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 25, in lookup\n",
      "    session['tweets'].append(tweet)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\werkzeug\\local.py\", line 377, in <lambda>\n",
      "    __getitem__ = lambda x, i: x._get_current_object()[i]\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\sessions.py\", line 83, in __getitem__\n",
      "    return super(SecureCookieSession, self).__getitem__(key)\n",
      "KeyError: 'tweets'\n",
      "127.0.0.1 - - [24/Mar/2019 12:30:07] \"\u001b[1m\u001b[35mPOST /user HTTP/1.1\u001b[0m\" 500 -\n",
      "[2019-03-24 12:30:07,921] ERROR in app: Exception on /signUp [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 13, in signUp\n",
      "    return json.dumps({'html':'<span>All fields good!</span>'})\n",
      "NameError: name 'json' is not defined\n",
      "127.0.0.1 - - [24/Mar/2019 12:30:07] \"\u001b[1m\u001b[35mPOST /signUp HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "yes u r here\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[2019-03-24 12:30:13,147] ERROR in app: Exception on /user [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 25, in lookup\n",
      "    session['tweets'].append(tweet)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\werkzeug\\local.py\", line 377, in <lambda>\n",
      "    __getitem__ = lambda x, i: x._get_current_object()[i]\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\sessions.py\", line 83, in __getitem__\n",
      "    return super(SecureCookieSession, self).__getitem__(key)\n",
      "KeyError: 'tweets'\n",
      "127.0.0.1 - - [24/Mar/2019 12:30:13] \"\u001b[1m\u001b[35mPOST /user HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "yes u r here\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/Mar/2019 12:30:17] \"\u001b[37mGET /home HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:30:17] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:30:21] \"\u001b[37mGET /showSignUp HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:30:22] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "[2019-03-24 12:30:26,191] ERROR in app: Exception on /user [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 25, in lookup\n",
      "    session['tweets'].append(tweet)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\werkzeug\\local.py\", line 377, in <lambda>\n",
      "    __getitem__ = lambda x, i: x._get_current_object()[i]\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\sessions.py\", line 83, in __getitem__\n",
      "    return super(SecureCookieSession, self).__getitem__(key)\n",
      "KeyError: 'tweets'\n",
      "127.0.0.1 - - [24/Mar/2019 12:30:26] \"\u001b[1m\u001b[35mPOST /user HTTP/1.1\u001b[0m\" 500 -\n",
      "[2019-03-24 12:30:26,204] ERROR in app: Exception on /signUp [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 13, in signUp\n",
      "    return json.dumps({'html':'<span>All fields good!</span>'})\n",
      "NameError: name 'json' is not defined\n",
      "127.0.0.1 - - [24/Mar/2019 12:30:26] \"\u001b[1m\u001b[35mPOST /signUp HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "yes u r here\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/Mar/2019 12:30:35] \"\u001b[37mGET /home HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:30:35] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:30:41] \"\u001b[37mGET /showSignUp HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:30:41] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "[2019-03-24 12:30:45,236] ERROR in app: Exception on /user [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 25, in lookup\n",
      "    session['tweets'].append(tweet)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\werkzeug\\local.py\", line 377, in <lambda>\n",
      "    __getitem__ = lambda x, i: x._get_current_object()[i]\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\sessions.py\", line 83, in __getitem__\n",
      "    return super(SecureCookieSession, self).__getitem__(key)\n",
      "KeyError: 'tweets'\n",
      "127.0.0.1 - - [24/Mar/2019 12:30:45] \"\u001b[1m\u001b[35mPOST /user HTTP/1.1\u001b[0m\" 500 -\n",
      "[2019-03-24 12:30:45,248] ERROR in app: Exception on /signUp [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 13, in signUp\n",
      "    return json.dumps({'html':'<span>All fields good!</span>'})\n",
      "NameError: name 'json' is not defined\n",
      "127.0.0.1 - - [24/Mar/2019 12:30:45] \"\u001b[1m\u001b[35mPOST /signUp HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "yes u r here\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/Mar/2019 12:30:49] \"\u001b[37mGET /home HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:30:50] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:30:54] \"\u001b[37mGET /showSignUp HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:30:55] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "[2019-03-24 12:31:02,335] ERROR in app: Exception on /user [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 25, in lookup\n",
      "    session['tweets'].append(tweet)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\werkzeug\\local.py\", line 377, in <lambda>\n",
      "    __getitem__ = lambda x, i: x._get_current_object()[i]\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\sessions.py\", line 83, in __getitem__\n",
      "    return super(SecureCookieSession, self).__getitem__(key)\n",
      "KeyError: 'tweets'\n",
      "127.0.0.1 - - [24/Mar/2019 12:31:02] \"\u001b[1m\u001b[35mPOST /user HTTP/1.1\u001b[0m\" 500 -\n",
      "[2019-03-24 12:31:02,341] ERROR in app: Exception on /signUp [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 13, in signUp\n",
      "    return json.dumps({'html':'<span>All fields good!</span>'})\n",
      "NameError: name 'json' is not defined\n",
      "127.0.0.1 - - [24/Mar/2019 12:31:02] \"\u001b[1m\u001b[35mPOST /signUp HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "yes u r here\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/Mar/2019 12:35:34] \"\u001b[37mGET /home HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:35:34] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:35:38] \"\u001b[37mGET /showSignUp HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:35:38] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "[2019-03-24 12:35:43,313] ERROR in app: Exception on /user [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 25, in lookup\n",
      "    session['tweets'].append(tweet)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\werkzeug\\local.py\", line 377, in <lambda>\n",
      "    __getitem__ = lambda x, i: x._get_current_object()[i]\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\sessions.py\", line 83, in __getitem__\n",
      "    return super(SecureCookieSession, self).__getitem__(key)\n",
      "KeyError: 'tweets'\n",
      "127.0.0.1 - - [24/Mar/2019 12:35:43] \"\u001b[1m\u001b[35mPOST /user HTTP/1.1\u001b[0m\" 500 -\n",
      "[2019-03-24 12:35:43,338] ERROR in app: Exception on /signUp [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 13, in signUp\n",
      "    return json.dumps({'html':'<span>All fields good!</span>'})\n",
      "NameError: name 'json' is not defined\n",
      "127.0.0.1 - - [24/Mar/2019 12:35:43] \"\u001b[1m\u001b[35mPOST /signUp HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "yes u r here\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [24/Mar/2019 12:37:02] \"\u001b[37mGET /home HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:37:03] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:40:26] \"\u001b[37mGET /home HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:40:26] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:40:29] \"\u001b[37mGET /showSignUp HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [24/Mar/2019 12:40:30] \"\u001b[33mGET /static/css/bootstrap.min.css.map HTTP/1.1\u001b[0m\" 404 -\n",
      "[2019-03-24 12:40:32,982] ERROR in app: Exception on /user [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 25, in lookup\n",
      "    session['tweets'].append(tweet)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\werkzeug\\local.py\", line 377, in <lambda>\n",
      "    __getitem__ = lambda x, i: x._get_current_object()[i]\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\sessions.py\", line 83, in __getitem__\n",
      "    return super(SecureCookieSession, self).__getitem__(key)\n",
      "KeyError: 'tweets'\n",
      "127.0.0.1 - - [24/Mar/2019 12:40:32] \"\u001b[1m\u001b[35mPOST /user HTTP/1.1\u001b[0m\" 500 -\n",
      "[2019-03-24 12:40:32,996] ERROR in app: Exception on /signUp [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-ccf3a9947eb5>\", line 13, in signUp\n",
      "    return json.dumps({'html':'<span>All fields good!</span>'})\n",
      "NameError: name 'json' is not defined\n",
      "127.0.0.1 - - [24/Mar/2019 12:40:33] \"\u001b[1m\u001b[35mPOST /signUp HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "yes u r here\n"
     ]
    }
   ],
   "source": [
    "from flask import Flask, flash, redirect, render_template, request, session, abort\n",
    "\n",
    "app = Flask(__name__)\n",
    "\n",
    "@app.route('/home')\n",
    "def index():\n",
    "    return render_template('index.html')\n",
    "\n",
    "@app.route('/signUp', methods=[\"GET\", \"POST\"])\n",
    "def signUp():\n",
    "    _name = request.form['inputName']\n",
    "    if _name:\n",
    "        return json.dumps({'html':'<span>All fields good!</span>'})\n",
    "    else:\n",
    "        return json.dumps({'html':'<span>Enter the required fields</span>'})\n",
    "\n",
    "@app.route('/user', methods=[\"GET\", \"POST\"])\n",
    "def lookup():\n",
    "    print('yes u r here')\n",
    "    h1 = 'Tweets'\n",
    "    title = 'Flask-Twitter'\n",
    "    _name = request.form['inputName']\n",
    "    tweet = {}\n",
    "    session['_name'] = _name\n",
    "    session['tweets'].append(tweet)\n",
    "    return render_template('user.html', h1=h1, title=title, _name=_name)\n",
    "\n",
    "    \n",
    "@app.route('/showSignUp')\n",
    "def showSignUp():\n",
    "    return render_template('signUp.html')\n",
    "\n",
    "@app.route('/tweets',methods=['POST'])\n",
    "def tweets():\n",
    "    return render_template('tweets.html')\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "if __name__=='__main__':\n",
    "    app.secret_key = 'super secret key'\n",
    "    #app.config['SESSION_TYPE'] = 'filesystem' \n",
    "    app.run()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 51,
   "metadata": {},
   "outputs": [
    {
     "ename": "SystemExit",
     "evalue": "1",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mSystemExit\u001b[0m                                Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-50-93ab8fed8d80>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m     42\u001b[0m     \u001b[1;31m#app.config['SESSION_TYPE'] = 'filesystem'\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     43\u001b[0m     \u001b[0mapp\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mdebug\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;32mTrue\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 44\u001b[1;33m     \u001b[0mapp\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mrun\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;32mC:\\ProgramData\\Anaconda2\\lib\\site-packages\\flask\\app.py\u001b[0m in \u001b[0;36mrun\u001b[1;34m(self, host, port, debug, load_dotenv, **options)\u001b[0m\n\u001b[0;32m    941\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    942\u001b[0m         \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 943\u001b[1;33m             \u001b[0mrun_simple\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mhost\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mport\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0moptions\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    944\u001b[0m         \u001b[1;32mfinally\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    945\u001b[0m             \u001b[1;31m# reset the first request information if the development server\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mC:\\ProgramData\\Anaconda2\\lib\\site-packages\\werkzeug\\serving.py\u001b[0m in \u001b[0;36mrun_simple\u001b[1;34m(hostname, port, application, use_reloader, use_debugger, use_evalex, extra_files, reloader_interval, reloader_type, threaded, processes, request_handler, static_files, passthrough_errors, ssl_context)\u001b[0m\n\u001b[0;32m    810\u001b[0m         \u001b[1;32mfrom\u001b[0m \u001b[0mwerkzeug\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_reloader\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mrun_with_reloader\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    811\u001b[0m         run_with_reloader(inner, extra_files, reloader_interval,\n\u001b[1;32m--> 812\u001b[1;33m                           reloader_type)\n\u001b[0m\u001b[0;32m    813\u001b[0m     \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    814\u001b[0m         \u001b[0minner\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mC:\\ProgramData\\Anaconda2\\lib\\site-packages\\werkzeug\\_reloader.py\u001b[0m in \u001b[0;36mrun_with_reloader\u001b[1;34m(main_func, extra_files, interval, reloader_type)\u001b[0m\n\u001b[0;32m    273\u001b[0m             \u001b[0mreloader\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mrun\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    274\u001b[0m         \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 275\u001b[1;33m             \u001b[0msys\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mexit\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mreloader\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mrestart_with_reloader\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    276\u001b[0m     \u001b[1;32mexcept\u001b[0m \u001b[0mKeyboardInterrupt\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    277\u001b[0m         \u001b[1;32mpass\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mSystemExit\u001b[0m: 1"
     ]
    }
   ],
   "source": [
    "%tb"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
